### ISSUE TITLE
What am I supposed to do now?

### ISSUE THREAD

**Issue by joeljuca** [torto/curriculo#1]
I'm stuck on the screen below and I can't really go anywhere from it:

![captura de tela 2016-09-13 19 48 45](https://cloud.githubusercontent.com/assets/673884/18494216/524149a8-79eb-11e6-8410-7b8c27db9fe8.png)

Is it a bug or a feature? :-P

**Comment by joeljuca** [comment]
FYI, I'm using Safari 9.1.2 on OS X El Capitan (10.11.6)

**Comment by torto** [comment]
@joelwallis I use linux and I can not test this version safari but I read that Safari does not support OGG, added a mp3 file.
Check and see if it works?
Commit:  bbd6c3c00502f0bc620d3ad39d29b15499981d21

**Comment by torto** [comment]
New commit: 6c3dbdd78a428506a067ccba71ba7427c2eef91a
Finaly working :heart:
